# Generated by Django 5.2.4 on 2025-07-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rsvp_comment_alter_rsvp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
